PRAGMA FOREIGN_KEYS = ON;
DROP TABLE IF EXISTS SEMESTER;
DROP TABLE IF EXISTS TIMEOFF;
DROP TABLE IF EXISTS APPOINTMENT;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS TUTORAVAILABILITY;
DROP TABLE IF EXISTS TUTORCOURSE;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS TUTOR;

CREATE TABLE TUTOR(
	TUTORID TEXT PRIMARY KEY NOT NULL 
   		CHECK(LENGTH(TUTORID) = 10 AND TUTORID GLOB '[0-9]*'), /*ENSURES ID NUMBER IS POSITIVE AND EXACTLY 10 DIGITS*/
   	FIRSTNAME TEXT NOT NULL CHECK(LENGTH(FIRSTNAME) <= 50),
   	LASTNAME TEXT NOT NULL CHECK(LENGTH(LASTNAME) <= 50),
   	BIO TEXT CHECK(LENGTH(BIO) <= 250),
   	PICTURE TEXT CHECK(PICTURE LIKE "_%.PNG" OR PICTURE LIKE "_%.JPG" OR PICTURE LIKE "_%.JPEG") /*ENSURES PICTURE IS ALWAYS A IMG PATH*/
);

CREATE TABLE COURSE(
	COURSECODE TEXT PRIMARY KEY NOT NULL
   		CHECK(LENGTH(COURSECODE) <= 7),
   	NAME TEXT NOT NULL CHECK(LENGTH(NAME) <= 50)
);

CREATE TABLE TUTORCOURSE(
	TUTORID TEXT CHECK(LENGTH(TUTORID) = 10 AND TUTORID GLOB '[0-9]*'),
	COURSECODE TEXT CHECK(LENGTH(COURSECODE) <= 7),
	PRIMARY KEY (TUTORID, COURSECODE),
	FOREIGN KEY(TUTORID) REFERENCES TUTOR(TUTORID),
	FOREIGN KEY(COURSECODE) REFERENCES COURSE(COURSECODE)
);

CREATE TABLE TUTORAVAILABILITY(
	TUTORID TEXT CHECK(LENGTH(TUTORID) = 10 AND TUTORID GLOB '[0-9]*'),
	WEEKDAY TEXT NOT NULL CHECK(
   						LOWER(WEEKDAY) IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
	STARTTIME TEXT NOT NULL CHECK(
   						CAST(SUBSTR(STARTTIME, 1, 2) AS INTEGER) BETWEEN 0 AND 23
        				AND CAST(SUBSTR(STARTTIME, 4, 2) AS INTEGER) BETWEEN 0 AND 59 /*VALIDATES TIMESTAMP TO HH:MM*/
        				AND SUBSTR(STARTTIME, 3, 1) = ':'), 
	ENDTIME TEXT NOT NULL CHECK(
   						CAST(SUBSTR(ENDTIME, 1, 2) AS INTEGER) BETWEEN 0 AND 23
        				AND CAST(SUBSTR(ENDTIME, 4, 2) AS INTEGER) BETWEEN 0 AND 59
        				AND SUBSTR(ENDTIME, 3, 1) = ':'),
	CHECK (ENDTIME > STARTTIME),
	PRIMARY KEY (TUTORID, WEEKDAY),
	FOREIGN KEY(TUTORID) REFERENCES TUTOR(TUTORID)
);

CREATE TABLE STUDENT(
	STUDENTEMAIL TEXT PRIMARY KEY NOT NULL
   		CHECK(LENGTH(STUDENTEMAIL) <= 50 AND STUDENTEMAIL LIKE '%_@_%._%'), /*VALIDATES EMAIL TO CHAR1+@CHAR1+.CHAR1+*/
	FIRSTNAME TEXT NOT NULL CHECK(LENGTH(FIRSTNAME) <= 50),
	LASTNAME TEXT NOT NULL CHECK(LENGTH(LASTNAME) <= 50)
);

CREATE TABLE APPOINTMENT(
	TUTORID TEXT CHECK(LENGTH(TUTORID) = 10 AND TUTORID GLOB '[0-9]*'),
	[DATE] TEXT NOT NULL CHECK(
			CAST(SUBSTR([DATE], 6, 2) AS INTEGER) BETWEEN 1 AND 12 /*VALIDATES TIMESTAMP TO YYYY-MM-DD*/ 
			AND CAST(SUBSTR([DATE], 9, 2) AS INTEGER) BETWEEN 1 AND 31 /*NEED TRIGGER TO ENFORCE THAT YEAR IS CURRENT OR FUTURE*/
			AND SUBSTR([DATE], 5, 1) = '-'
			AND SUBSTR([DATE], 8, 1) = '-'),
	[TIME] TEXT NOT NULL CHECK(
			CAST(SUBSTR([TIME], 1, 2) AS INTEGER) BETWEEN 0 AND 23
			AND CAST(SUBSTR([TIME], 4, 2) AS INTEGER) BETWEEN 0 AND 59
			AND SUBSTR([TIME], 3, 1) = ':'),
	STUDENTEMAIL TEXT NOT NULL CHECK(LENGTH(STUDENTEMAIL) <= 50 AND STUDENTEMAIL LIKE '%_@_%._%'),
	COURSECODE TEXT NOT NULL CHECK(LENGTH(COURSECODE) <= 7),
	PRIMARY KEY (TUTORID, [DATE], [TIME]),
	FOREIGN KEY(TUTORID) REFERENCES TUTOR(TUTORID),
	FOREIGN KEY(COURSECODE) REFERENCES COURSE(COURSECODE),
	FOREIGN KEY(STUDENTEMAIL) REFERENCES STUDENT(STUDENTEMAIL)
);

CREATE TABLE TIMEOFF (
	TUTORID TEXT,
	[DATE] TEXT NOT NULL CHECK(
			CAST(SUBSTR([DATE], 6, 2) AS INTEGER) BETWEEN 1 AND 12 /*VALIDATES TIMESTAMP TO YYYY-MM-DD*/ 
			AND CAST(SUBSTR([DATE], 9, 2) AS INTEGER) BETWEEN 1 AND 31 
			AND SUBSTR([DATE], 5, 1) = '-'
			AND SUBSTR([DATE], 8, 1) = '-'),
	REASON TEXT NOT NULL CHECK(LENGTH(REASON) < 50),
	PRIMARY KEY (TUTORID, [DATE])
);

CREATE TABLE SEMESTER (
	ID INTEGER PRIMARY KEY NOT NULL, 
	NAME TEXT NOT NULL, 
	STARTDATE TEXT NOT NULL CHECK(
			CAST(SUBSTR(STARTDATE, 6, 2) AS INTEGER) BETWEEN 1 AND 12 /*VALIDATES TIMESTAMP TO YYYY-MM-DD*/ 
			AND CAST(SUBSTR(STARTDATE, 9, 2) AS INTEGER) BETWEEN 1 AND 31 
			AND SUBSTR(STARTDATE, 5, 1) = '-'
			AND SUBSTR(STARTDATE, 8, 1) = '-'),
	ENDDATE TEXT NOT NULL CHECK(
			CAST(SUBSTR(ENDDATE, 6, 2) AS INTEGER) BETWEEN 1 AND 12 /*VALIDATES TIMESTAMP TO YYYY-MM-DD*/ 
			AND CAST(SUBSTR(ENDDATE, 9, 2) AS INTEGER) BETWEEN 1 AND 31 
			AND SUBSTR(ENDDATE, 5, 1) = '-'
			AND SUBSTR(ENDDATE, 8, 1) = '-'),
	ACTIVE INTEGER NOT NULL CHECK(ACTIVE = 0 OR ACTIVE = 1)/*SQLITE DOES NOT HAVE A BOOL DATATYPE (THIS WILL BE TREATED AS BOOL 1 OR 0)*/
);